<template>
  <section class="support-wrapper">
    <div class="u-text-center">
      <button
        class="button u-margin-inline-auto u-margin-block-start-24"
        @click="showModal = true"
      >
        <span class="icon-annotation"></span>
      </button>
      <div v-if="showModal" class="modal-overlay" id="dialog">
        <div class="modal">
          <form
            class="modal-form"
            method="dialog"
          >
            <header class="modal-header">
              <h4 class="modal-title heading-level-5">Support</h4>
              <button
                class="button is-text is-small is-only-icon"
                aria-label="Close modal"
                @click="showModal = false"
              >
                <span class="icon-x" aria-hidden="true"></span>
              </button>
            </header>
            <div class="card" style="max-width: 500px; margin: auto">
              <div>
                <div class="u-text-center u-bold">Chat</div>
              </div>

              <ul class="u-padding-24" style="min-height: 300px">
                <li v-for="message in messages" class="message" :key="message">
                  <div class="message_wrapper">
                    <div>{{ avatar }}</div>
                    <div class="">{{ message }}</div>
                  </div>
                </li>
              </ul>

              <div>
                <div class="u-flex" style="max-width: 400px">
                  <div class="input">
                    <input
                      id="message-text-field"
                      class="u-max-width-500"
                      type="text"
                      placeholder="Type your message here..."
                      v-model="message"
                    />
                  </div>
                  <button
                    type="submit"
                    class="button"
                    @click="createChatIfNotExist"
                  >
                    Send
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
<!-- <template>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <main class="container u-height-100-percent u-main-center">
        <div class="u-main-center">
          <ReactPlayer
            style="max-width: 500px; min-height: 200px; margin: auto; padding-bottom: 10px"
            url="https://www.youtube.com/watch?v=xO9QDQaVHxU"
          />
        </div>

      </main>
    </div>
  </template> -->
<style>
.support-wrapper {
  position: fixed;
  bottom: 20px;
  right: 20px;
  z-index: 999;
}

.support-button {
  background-color: var(--color-primary-500);
  color: white;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 998; /* Lower z-index than the support button */
}
</style>
<script>
import { ref, onMounted } from "vue";
import { AvatarGenerator } from 'random-avatar-generator';
import {
  createAnonymousSession,
  databases,
  account,
  client,
} from "@/utils/web-init";
import "@appwrite.io/pink";
import "@appwrite.io/pink-icons";
import { ID } from "appwrite";

export default {
  name: "Support",
  setup() {
    const avatar = ref("");
    const messages = ref([]);
    const message = ref("");

    const createChatIfNotExist = async () => {
      console.log("Adding user", message);
      const promise = databases.createDocument(
        "647f17e626b622d99568",
        "647f17f6f3acb63bbace",
        "general-chat",
        {
          avatar: avatar.value,
          messages: [...messages.value, message.value],
        }
      );
      promise
        .then(function (response) {
          console.log("runnner", response); // Success
        })
        .catch(function (error) {
          console.log(error); // Failure
          databases.updateDocument(
            "647f17e626b622d99568",
            "647f17f6f3acb63bbace",
            "general-chat",
            {
              avatar: avatar.value,
              messages: [...messages.value, message.value],
            }
          );
        });
    };

    onMounted(async () => {
        if (!avatar.value) {
        const _avatar = localStorage.getItem('avatar') || new AvatarGenerator().generateRandomAvatar();
        localStorage.setItem('avatar', _avatar);
        avatar.value = _avatar;
        console.log(_avatar);
      }

      const result = await databases.getDocument(
        "647f17e626b622d99568",
        "647f17f6f3acb63bbace",
        "general-chat"
      );
      messages.value = result.messages;
    });

    onMounted(() => {
      console.log("anything");
      // Subscribe to collection channel
      const _subscribe = client.subscribe(
        "databases.647f17e626b622d99568.collections.647f17f6f3acb63bbace.documents",
        (response) => {
          console.log("iiiii", response);
          const { payload } = response;
          if (payload?.$id === "general-chat") {
            messages.value = payload.messages;
          }
        }
      );
      return () => {
        _subscribe();
      };
    });

    onMounted(() => {
      createAnonymousSession();
    });

    return {
      avatar,
      messages,
      message,
      createChatIfNotExist,
    };
  },
};
</script>
